add clear log script
ccmp/ubuntu_setup_on_debian_buster pull request #2
Opened 2021-03-24 10:47 UTC by kmoriya-ccmp

2021-03-29 04:46 UTC, ktaka-ccmp requested changes

2021-03-29 04:46 UTC, ktaka-ccmp commented on clearlog.sh
> +    mount /dev/nvme0n1p1 ${ROOTMNT}
ここ修正お願いします。

2021-03-29 04:46 UTC, ktaka-ccmp commented on createimg.sh
> +dconf write /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-system-font false
このUUIDは他のマシンでも同じになるんですか？

2021-04-09 08:31 UTC, ktaka-ccmp commented
@kmoriya-ccmp  守屋さん、確認お願いします。

2021-04-09 08:42 UTC, kmoriya-ccmp commented on clearlog.sh
> +    mount /dev/nvme0n1p1 ${ROOTMNT}
修正しておきました。

2021-04-09 08:49 UTC, kmoriya-ccmp commented on createimg.sh
> +dconf write /org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-system-font false
そのUUIDはすべてのマシンで同じになるようです。インストールイメージを作成する際(debootstrapでgnome-terminalのパッケージをルートイメージにインストールする際)に決定されているようです。

2021-04-09 08:58 UTC, merged