Moriya
ccmp/ubuntu_setup_on_debian_buster pull request #4
Opened 2022-02-09 09:19 UTC by kmoriya-ccmp

ubuntu_install.shスクリプト修正
 * nvme/sataどちらでも対応できるように変更
Readme追記
clearlog.shスクリプト修正
 * nvme/sataどちらでも対応できるように変更

2022-02-16 06:12 UTC, ktaka-ccmp requested changes
@kmoriya-ccmp 修正お願いします。

以下のページへのリンクもReadmeに入れておいてもらえますか？
https://trac.ccmp.jp/clustcom/wiki/riken20220204#no1

2022-02-16 06:12 UTC, ktaka-ccmp commented on Readme.md
> + * ubuntu_install.shスクリプトを改修したので以下の手順はもう必要ない、
もう必要ないなら、消していいと思います。

2022-02-16 06:12 UTC, ktaka-ccmp commented on ubuntu_install.sh
> +DRV=$2
$DRVどこかで使ってますか？

2022-02-17 01:31 UTC, kmoriya-ccmp commented on Readme.md
> + * ubuntu_install.shスクリプトを改修したので以下の手順はもう必要ない、
削除しておきました

2022-02-17 01:35 UTC, kmoriya-ccmp commented
https://trac.ccmp.jp/clustcom/wiki/riken20220204#no1へのリンク追加しました。

2022-02-25 05:15 UTC, merged